import { adminApi } from '@/api/client';

export type SeoEntityType = 'CITY' | 'EVENT' | 'VENUE' | 'LANDING' | 'ARTICLE' | 'COMBO';

export type SeoMetaResponse = {
  entityType: SeoEntityType;
  entityId: string;
  title: string | null;
  description: string | null;
  h1: string | null;
  canonicalUrl: string | null;
  robots: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;
  jsonLd: Record<string, unknown> | null;
  autoGenerated: boolean;
  source: 'manual' | 'auto' | 'default';
};

export type UpsertSeoMetaDto = {
  title?: string | null;
  description?: string | null;
  h1?: string | null;
  canonicalUrl?: string | null;
  robots?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: string | null;
  jsonLd?: Record<string, unknown> | null;
  autoGenerated?: boolean;
};

export function getSeo(entityType: SeoEntityType, entityId: string): Promise<SeoMetaResponse> {
  return adminApi.get<SeoMetaResponse>(`/admin/seo/${entityType}/${entityId}`);
}

export function upsertSeo(
  entityType: SeoEntityType,
  entityId: string,
  dto: UpsertSeoMetaDto,
): Promise<SeoMetaResponse> {
  return adminApi.put<SeoMetaResponse>(`/admin/seo/${entityType}/${entityId}`, dto);
}

export function generateSeo(entityType: SeoEntityType, entityId: string): Promise<SeoMetaResponse> {
  return adminApi.post<SeoMetaResponse>(`/admin/seo/${entityType}/${entityId}/generate`);
}
