import { createHash } from 'crypto';

import { Injectable, NotFoundException } from '@nestjs/common';
import { SubcategoryLandingMode, SubcategoryType } from '@prisma/client';

import { cacheKeys } from '../cache/cache-keys';
import { CacheService } from '../cache/cache.service';
import { PrismaService } from '../prisma/prisma.service';
import {
  SUBCATEGORY_COLLECTION_THRESHOLDS,
  subcategoryCollectionCacheTtlSec,
} from './subcategory-collections.constants';
import {
  SubcategoryCollectionEntityKind,
  SubcategoryCollectionsService,
} from './subcategory-collections.service';
import { topicHubRedirectPath } from './subcategory-landing-topic-hubs';

export interface SubcategoryLandingBreadcrumb {
  label: string;
  href: string;
}

export interface SubcategoryLandingDefinition {
  key: string;
  entityKind: SubcategoryCollectionEntityKind;
  subcategoryCode: string;
  subcategorySlug: string;
  cityId: string;
  citySlug: string;
  cityName: string;
  title: string;
  h1: string;
  description: string;
  canonicalPath: string;
  breadcrumbs: SubcategoryLandingBreadcrumb[];
  introText: string;
  seoEnabled: boolean;
  isAutoGenerated: true;
}

export interface SubcategoryLandingPublicPayload {
  published: boolean;
  /** Причины непубликации (для админского preview) */
  unpublishedReasons: string[];
  /** Если задано — канонический тематический маршрут вместо generic subcategory landing. */
  topicHubRedirect?: string | null;
  definition: SubcategoryLandingDefinition;
  entityKind: SubcategoryCollectionEntityKind;
  collection: {
    total: number;
    items: unknown[];
    page: number;
    totalPages: number;
  };
  relatedLandings: Array<{
    slug: string;
    nameRu: string;
    href: string;
    entityKind: SubcategoryCollectionEntityKind;
  }>;
}

function inferEntityKind(type: SubcategoryType): SubcategoryCollectionEntityKind {
  if (type === SubcategoryType.VENUE_ONLY) return 'VENUE';
  return 'EVENT';
}

function stableHash(parts: Record<string, unknown>): string {
  return createHash('sha256').update(JSON.stringify(parts)).digest('hex').slice(0, 32);
}

@Injectable()
export class SubcategoryLandingService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly collections: SubcategoryCollectionsService,
    private readonly cache: CacheService,
  ) {}

  private buildSeoCopy(params: {
    nameRu: string;
    cityName: string;
    entityKind: SubcategoryCollectionEntityKind;
  }) {
    const { nameRu, cityName, entityKind } = params;
    const h1 =
      entityKind === 'VENUE'
        ? `${nameRu} в ${cityName}`
        : `${nameRu} в ${cityName}`;
    const title =
      entityKind === 'VENUE'
        ? `${nameRu} в ${cityName} — подборка площадок и музеев`
        : `${nameRu} в ${cityName} — афиша, цены и бронирование`;
    const description =
      entityKind === 'VENUE'
        ? `Подборка «${nameRu}» в ${cityName}: музеи и площадки на одной странице. Сравните варианты и выберите место.`
        : `«${nameRu}» в ${cityName}: актуальные события, расписание и билеты. Удобный каталог на Дайбилет.`;
    const introText =
      entityKind === 'VENUE'
        ? `Собрали площадки в категории «${nameRu}» в городе ${cityName}.`
        : `Собрали события в направлении «${nameRu}» в городе ${cityName}.`;
    return { h1, title, description, introText };
  }

  /**
   * Соседние подкатегории (тот же parent) с включённым лендингом — для внутренней перелинковки.
   */
  private async relatedSiblings(
    subcategoryId: string,
    parentId: string | null,
    type: SubcategoryType,
    citySlug: string,
    selfSlug: string,
  ): Promise<SubcategoryLandingPublicPayload['relatedLandings']> {
    if (!parentId) return [];

    const siblings = await this.prisma.subcategory.findMany({
      where: {
        id: { not: subcategoryId },
        parentId,
        type,
        isActive: true,
        isLandingEnabled: true,
        landingMode: SubcategoryLandingMode.AUTO,
      },
      select: { slug: true, nameRu: true, type: true },
      orderBy: [{ sortOrder: 'asc' }, { nameRu: 'asc' }],
      take: 12,
    });

    return siblings
      .filter((s) => s.slug !== selfSlug)
      .map((s) => ({
        slug: s.slug,
        nameRu: s.nameRu,
        href: `/cities/${citySlug}/${s.slug}`,
        entityKind: inferEntityKind(s.type),
      }));
  }

  private evaluatePublication(params: {
    subActive: boolean;
    landingEnabled: boolean;
    cityActive: boolean;
    total: number;
    entityKind: SubcategoryCollectionEntityKind;
  }): { published: boolean; reasons: string[] } {
    const reasons: string[] = [];
    if (!params.subActive) reasons.push('SUBCATEGORY_INACTIVE');
    if (!params.landingEnabled) reasons.push('LANDING_DISABLED');
    if (!params.cityActive) reasons.push('CITY_INACTIVE');
    const min =
      params.entityKind === 'VENUE'
        ? SUBCATEGORY_COLLECTION_THRESHOLDS.landingMinVenues
        : SUBCATEGORY_COLLECTION_THRESHOLDS.landingMinEvents;
    if (params.total < min) reasons.push('BELOW_CONTENT_THRESHOLD');

    return {
      published: reasons.length === 0,
      reasons,
    };
  }

  /**
   * Полный payload (публичный и админский preview). Для публичного вызова смотри getPublishedLandingOrThrow.
   */
  async buildLandingPayload(
    citySlug: string,
    subcategorySlug: string,
    options?: { nocache?: boolean; limit?: number },
  ): Promise<SubcategoryLandingPublicPayload> {
    const nocache = options?.nocache === true;
    const limit = options?.limit ?? 36;

    const hash = stableHash({ citySlug, subcategorySlug, limit });
    const cacheKey = cacheKeys.subcategoryCollections.landing(hash);
    const ttl = subcategoryCollectionCacheTtlSec();

    const fetcher = async (): Promise<SubcategoryLandingPublicPayload> => {
      const [city, sub] = await Promise.all([
        this.prisma.city.findFirst({
          where: { slug: citySlug, isActive: true },
          select: { id: true, slug: true, name: true, isActive: true },
        }),
        this.prisma.subcategory.findFirst({
          where: { slug: subcategorySlug },
          select: {
            id: true,
            code: true,
            slug: true,
            nameRu: true,
            type: true,
            isActive: true,
            isLandingEnabled: true,
            landingMode: true,
            landingTopicKey: true,
            parentId: true,
          },
        }),
      ]);

      if (!city) {
        return this.emptyPayload('CITY_NOT_FOUND', citySlug, subcategorySlug);
      }
      if (!sub) {
        return this.emptyPayload('SUBCATEGORY_NOT_FOUND', citySlug, subcategorySlug);
      }

      if (sub.landingMode === SubcategoryLandingMode.TOPIC_HUB) {
        const topicHubRedirect = topicHubRedirectPath(sub.landingTopicKey, city.slug);
        const entityKind = inferEntityKind(sub.type);
        const seo = this.buildSeoCopy({ nameRu: sub.nameRu, cityName: city.name, entityKind });
        const canonicalPath = `/cities/${city.slug}/${sub.slug}`;
        return {
          published: false,
          unpublishedReasons: ['TOPIC_HUB_CANONICAL'],
          topicHubRedirect,
          definition: {
            key: `subcat:topic-hub:${sub.code}:${city.slug}`,
            entityKind,
            subcategoryCode: sub.code,
            subcategorySlug: sub.slug,
            cityId: city.id,
            citySlug: city.slug,
            cityName: city.name,
            title: seo.title,
            h1: seo.h1,
            description: seo.description,
            canonicalPath,
            breadcrumbs: [
              { label: 'Главная', href: '/' },
              { label: city.name, href: `/cities/${city.slug}` },
              { label: sub.nameRu, href: canonicalPath },
            ],
            introText: seo.introText,
            seoEnabled: false,
            isAutoGenerated: true,
          },
          entityKind,
          collection: { total: 0, items: [], page: 1, totalPages: 0 },
          relatedLandings: [],
        };
      }

      if (sub.landingMode !== SubcategoryLandingMode.AUTO) {
        return this.emptyPayload('LANDING_MODE_DISABLED', citySlug, subcategorySlug);
      }

      const entityKind = inferEntityKind(sub.type);

      const collectionParams = {
        subcategoryCode: sub.code,
        citySlug: city.slug,
        cityId: city.id,
        page: 1,
        limit,
        nocache,
      };

      const coll =
        entityKind === 'VENUE'
          ? await this.collections.getVenueCollectionBySubcategory(collectionParams)
          : await this.collections.getEventCollectionBySubcategory(collectionParams);

      const total = coll.total ?? 0;
      const items = coll.items ?? [];
      const totalPages = coll.totalPages ?? 0;

      const { published, reasons } = this.evaluatePublication({
        subActive: sub.isActive,
        landingEnabled: sub.isLandingEnabled,
        cityActive: city.isActive,
        total,
        entityKind,
      });

      const seo = this.buildSeoCopy({ nameRu: sub.nameRu, cityName: city.name, entityKind });
      const canonicalPath = `/cities/${city.slug}/${sub.slug}`;

      const definition: SubcategoryLandingDefinition = {
        key: `subcat:${sub.code}:${city.slug}:${entityKind}`,
        entityKind,
        subcategoryCode: sub.code,
        subcategorySlug: sub.slug,
        cityId: city.id,
        citySlug: city.slug,
        cityName: city.name,
        title: seo.title,
        h1: seo.h1,
        description: seo.description,
        canonicalPath,
        breadcrumbs: [
          { label: 'Главная', href: '/' },
          { label: city.name, href: `/cities/${city.slug}` },
          { label: sub.nameRu, href: canonicalPath },
        ],
        introText: seo.introText,
        seoEnabled: sub.isLandingEnabled,
        isAutoGenerated: true,
      };

      const relatedLandings = await this.relatedSiblings(sub.id, sub.parentId, sub.type, city.slug, sub.slug);

      return {
        published,
        unpublishedReasons: reasons,
        topicHubRedirect: null,
        definition,
        entityKind,
        collection: { total, items, page: 1, totalPages },
        relatedLandings,
      };
    };

    if (nocache) {
      return fetcher();
    }
    const cached = await this.cache.get<SubcategoryLandingPublicPayload>(cacheKey);
    if (cached) return cached;
    const fresh = await fetcher();
    if (fresh.published) {
      await this.cache.set(cacheKey, fresh, ttl);
    }
    return fresh;
  }

  private emptyPayload(
    reason: string,
    citySlug: string,
    subcategorySlug: string,
  ): SubcategoryLandingPublicPayload {
    const definition: SubcategoryLandingDefinition = {
      key: `subcat:missing:${citySlug}:${subcategorySlug}`,
      entityKind: 'EVENT',
      subcategoryCode: '',
      subcategorySlug,
      cityId: '',
      citySlug,
      cityName: '',
      title: 'Страница недоступна',
      h1: 'Страница недоступна',
      description: '',
      canonicalPath: `/cities/${citySlug}/${subcategorySlug}`,
      breadcrumbs: [
        { label: 'Главная', href: '/' },
        { label: citySlug, href: `/cities/${citySlug}` },
        { label: subcategorySlug, href: `/cities/${citySlug}/${subcategorySlug}` },
      ],
      introText: '',
      seoEnabled: false,
      isAutoGenerated: true,
    };

    return {
      published: false,
      unpublishedReasons: [reason],
      topicHubRedirect: null,
      definition,
      entityKind: 'EVENT',
      collection: { total: 0, items: [], page: 1, totalPages: 0 },
      relatedLandings: [],
    };
  }

  /**
   * Резолв маршрута до вызова полного payload: TOPIC_HUB → редирект на тематический хаб; AUTO → клиент может звать published API.
   */
  async resolvePublicRoute(
    citySlug: string,
    subcategorySlug: string,
  ): Promise<{ kind: 'NOT_FOUND' } | { kind: 'TOPIC_HUB'; redirectPath: string } | { kind: 'AUTO' }> {
    const city = await this.prisma.city.findFirst({
      where: { slug: citySlug, isActive: true },
      select: { slug: true },
    });
    if (!city) return { kind: 'NOT_FOUND' };

    const sub = await this.prisma.subcategory.findFirst({
      where: { slug: subcategorySlug },
      select: { landingMode: true, landingTopicKey: true, isActive: true },
    });
    if (!sub?.isActive) return { kind: 'NOT_FOUND' };

    if (sub.landingMode === SubcategoryLandingMode.TOPIC_HUB) {
      const redirectPath = topicHubRedirectPath(sub.landingTopicKey, city.slug);
      if (redirectPath) return { kind: 'TOPIC_HUB', redirectPath };
      return { kind: 'NOT_FOUND' };
    }
    if (sub.landingMode !== SubcategoryLandingMode.AUTO) return { kind: 'NOT_FOUND' };
    return { kind: 'AUTO' };
  }

  /** Публичная витрина: 404 если нет сущности или не прошли условия публикации. */
  async getPublishedLandingOrThrow(citySlug: string, subcategorySlug: string): Promise<SubcategoryLandingPublicPayload> {
    const payload = await this.buildLandingPayload(citySlug, subcategorySlug, { nocache: false });
    if (payload.unpublishedReasons.includes('CITY_NOT_FOUND') || payload.unpublishedReasons.includes('SUBCATEGORY_NOT_FOUND')) {
      throw new NotFoundException('Landing not found');
    }
    if (!payload.published) {
      throw new NotFoundException('Landing not published');
    }
    return payload;
  }
}
