import { api } from '@/lib/api';

export type SeoEntityType = 'CITY' | 'EVENT' | 'VENUE' | 'LANDING' | 'ARTICLE' | 'COMBO';

export type SeoMetaResponse = {
  entityType: SeoEntityType;
  entityId: string;
  title: string | null;
  description: string | null;
  h1: string | null;
  canonicalUrl: string | null;
  robots: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;
  jsonLd: Record<string, unknown> | null;
  autoGenerated: boolean;
  source?: 'manual' | 'auto' | 'default';
};

export async function getSeoMeta(entityType: SeoEntityType, entityId: string): Promise<SeoMetaResponse | null> {
  try {
    const res = await api.getSeoMeta(entityType, entityId);
    return res as SeoMetaResponse;
  } catch {
    return null;
  }
}
