version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: "your-secret-key"
      SECRET: "your-secret-secret"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "daibilet"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      ADMIN_EMAIL: "admin@daibilet.ru"
      ADMIN_PASSWORD: "StrongPassword123"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: daibilet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - directus_postgres:/var/lib/postgresql/data

volumes:
  directus_postgres: