import { useEffect, useMemo, useState } from 'react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { ImageUploadInput } from '@/components/ui/ImageUploadInput';
import { generateSeo, getSeo, SeoEntityType, SeoMetaResponse, upsertSeo } from '@/lib/api/seo';

type Props = {
  entityType: SeoEntityType;
  entityId: string;
  defaultTitle?: string;
  /**
   * Относительный путь страницы (для превью URL), например `/events/slug`.
   * Не влияет на canonicalUrl в БД, только на визуальный предпросмотр.
   */
  previewPath?: string;
};

export function SeoMetaEditor({ entityType, entityId, defaultTitle, previewPath }: Props) {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [data, setData] = useState<SeoMetaResponse | null>(null);
  const [form, setForm] = useState({
    title: '',
    description: '',
    h1: '',
    canonicalUrl: '',
    robots: '',
    ogTitle: '',
    ogDescription: '',
    ogImage: '',
    jsonLdText: '',
  });

  const counters = useMemo(
    () => ({
      title: form.title.length,
      description: form.description.length,
      h1: form.h1.length,
    }),
    [form],
  );

  useEffect(() => {
    let mounted = true;
    getSeo(entityType, entityId)
      .then((seo) => {
        if (!mounted) return;
        setData(seo);
        setForm({
          title: seo.title ?? defaultTitle ?? '',
          description: seo.description ?? '',
          h1: seo.h1 ?? '',
          canonicalUrl: seo.canonicalUrl ?? '',
          robots: seo.robots ?? '',
          ogTitle: seo.ogTitle ?? '',
          ogDescription: seo.ogDescription ?? '',
          ogImage: seo.ogImage ?? '',
          jsonLdText: seo.jsonLd ? JSON.stringify(seo.jsonLd, null, 2) : '',
        });
      })
      .catch(() => {
        if (mounted)
          setForm({
            title: defaultTitle ?? '',
            description: '',
            h1: '',
            canonicalUrl: '',
            robots: '',
            ogTitle: '',
            ogDescription: '',
            ogImage: '',
            jsonLdText: '',
          });
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [entityType, entityId, defaultTitle]);

  const onChange = (k: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm((p) => ({ ...p, [k]: e.target.value }));
  };

  const onGenerate = async () => {
    setSaving(true);
    try {
      const seo = await generateSeo(entityType, entityId);
      setData(seo);
      setForm({
        title: seo.title ?? '',
        description: seo.description ?? '',
        h1: seo.h1 ?? '',
        canonicalUrl: seo.canonicalUrl ?? '',
        robots: seo.robots ?? '',
        ogTitle: seo.ogTitle ?? '',
        ogDescription: seo.ogDescription ?? '',
        ogImage: seo.ogImage ?? '',
        jsonLdText: seo.jsonLd ? JSON.stringify(seo.jsonLd, null, 2) : '',
      });
    } finally {
      setSaving(false);
    }
  };

  const onSave = async () => {
    setSaving(true);
    try {
      let jsonLd: Record<string, unknown> | null = null;
      if (form.jsonLdText.trim()) {
        try {
          jsonLd = JSON.parse(form.jsonLdText);
        } catch {
          return;
        }
      }
      const payload = {
        title: form.title.trim() || null,
        description: form.description.trim() || null,
        h1: form.h1.trim() || null,
        canonicalUrl: form.canonicalUrl.trim() || null,
        robots: form.robots.trim() || null,
        ogTitle: form.ogTitle.trim() || null,
        ogDescription: form.ogDescription.trim() || null,
        ogImage: form.ogImage.trim() || null,
        jsonLd,
        autoGenerated: false,
      };
      const seo = await upsertSeo(entityType, entityId, payload);
      setData({ ...seo, source: 'manual' });
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="rounded-xl border border-gray-200 bg-white p-4 text-sm text-gray-600">Загрузка SEO…</div>;
  }

  const seoStatus = data?.source === 'manual' ? 'MANUAL' : data?.source === 'auto' ? 'AUTO' : 'DEFAULT';
  const titleLen = form.title.trim().length;
  const descLen = form.description.trim().length;
  const titleOk = titleLen >= 10;
  const descOk = descLen >= 50;

  // Рекомендованные лимиты
  const TITLE_SOFT_LIMIT = 60;
  const TITLE_HARD_LIMIT = 70;
  const DESC_SOFT_LIMIT = 160;
  const DESC_HARD_LIMIT = 180;

  const titleRatio = Math.min(1, titleLen / TITLE_SOFT_LIMIT);
  const descRatio = Math.min(1, descLen / DESC_SOFT_LIMIT);

  const titleColor =
    titleLen === 0
      ? 'bg-gray-200'
      : titleLen <= TITLE_SOFT_LIMIT
        ? 'bg-emerald-500'
        : titleLen <= TITLE_HARD_LIMIT
          ? 'bg-amber-500'
          : 'bg-red-500';

  const descColor =
    descLen === 0
      ? 'bg-gray-200'
      : descLen <= DESC_SOFT_LIMIT
        ? 'bg-emerald-500'
        : descLen <= DESC_HARD_LIMIT
          ? 'bg-amber-500'
          : 'bg-red-500';

  const displayHost = 'daibilet.ru';
  const displayPath = previewPath || '/events/slug';

  return (
    <div className="space-y-4 rounded-xl border border-gray-200 bg-white p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="text-sm font-semibold">SEO</div>
          <div className="text-xs text-gray-600">Источник: {seoStatus}</div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={onGenerate} disabled={saving}>
            Сгенерировать
          </Button>
          <Button size="sm" onClick={onSave} disabled={saving || !titleOk || !descOk}>
            Сохранить
          </Button>
        </div>
      </div>

      {/* Google-like preview */}
      <div className="rounded-lg border border-gray-200 bg-white p-4 text-xs shadow-sm">
        <div className="mb-1 text-[11px] text-gray-500">
          <span className="text-green-700">{displayHost}</span>
          <span className="text-gray-400"> › </span>
          <span className="text-gray-700">{displayPath}</span>
        </div>
        <div className="mt-0.5 text-sm font-medium text-blue-700">{form.title || 'Заголовок страницы'}</div>
        <div className="mt-1 text-[13px] leading-snug text-gray-700">
          {form.description || 'Краткое описание события для поисковой выдачи.'}
        </div>
      </div>

      <div className="grid gap-3">
        <div>
          <div className="mb-1 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Label>Meta title</Label>
              <span className="text-[10px] text-gray-500">рекомендуется ≤ {TITLE_SOFT_LIMIT}</span>
            </div>
            <span className={`text-xs ${titleLen > TITLE_HARD_LIMIT ? 'text-red-600' : 'text-gray-500'}`}>
              {titleLen}
            </span>
          </div>
          <div className="mb-1 h-1.5 w-full overflow-hidden rounded-full bg-gray-100">
            <div className={`h-full ${titleColor}`} style={{ width: `${titleRatio * 100}%` }} />
          </div>
          <Input value={form.title} onChange={onChange('title')} placeholder="До 60 символов" />
        </div>
        <div>
          <div className="mb-1 flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Label>Meta description</Label>
              <span className="text-[10px] text-gray-500">рекомендуется ≤ {DESC_SOFT_LIMIT}</span>
            </div>
            <span className={`text-xs ${descLen > DESC_HARD_LIMIT ? 'text-red-600' : 'text-gray-500'}`}>
              {descLen}
            </span>
          </div>
          <div className="mb-1 h-1.5 w-full overflow-hidden rounded-full bg-gray-100">
            <div className={`h-full ${descColor}`} style={{ width: `${descRatio * 100}%` }} />
          </div>
          <Textarea
            value={form.description}
            onChange={onChange('description')}
            rows={3}
            placeholder="До 160 символов"
          />
        </div>
        <div>
          <div className="mb-1 flex justify-between">
            <Label>H1</Label>
            <span className="text-xs text-gray-500">{counters.h1}/120</span>
          </div>
          <Input value={form.h1} onChange={onChange('h1')} />
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <Label>Canonical URL</Label>
            <Input value={form.canonicalUrl} onChange={onChange('canonicalUrl')} placeholder="Опционально" />
          </div>
          <div>
            <Label>Robots</Label>
            <Input value={form.robots} onChange={onChange('robots')} placeholder="index,follow" />
          </div>
        </div>
        <div className="grid gap-3 sm:grid-cols-3">
          <div>
            <Label>OG title</Label>
            <Input value={form.ogTitle} onChange={onChange('ogTitle')} />
          </div>
          <div className="sm:col-span-2">
            <Label>OG description</Label>
            <Input value={form.ogDescription} onChange={onChange('ogDescription')} />
          </div>
        </div>
        <ImageUploadInput
          label="OG image URL"
          value={form.ogImage}
          onChange={(v) => setForm((p) => ({ ...p, ogImage: v }))}
          placeholder="https://..."
        />
        <div>
          <Label>JSON-LD (опционально)</Label>
          <Textarea
            value={form.jsonLdText}
            onChange={onChange('jsonLdText')}
            rows={8}
            className="font-mono text-xs"
            placeholder='{"@context":"https://schema.org","@type":"Event",...}'
          />
        </div>
        {(!titleOk || !descOk) && (
          <p className="text-xs text-amber-700">Для сохранения: title ≥ 10 символов и description ≥ 50 символов.</p>
        )}
      </div>
    </div>
  );
}
