import { useEffect, useMemo, useState } from 'react';
import {
  SeoEntityType,
  SeoMetaResponse,
  generateSeo,
  getSeo,
  upsertSeo,
} from '@/lib/api/seo';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';

type Props = {
  entityType: SeoEntityType;
  entityId: string;
  defaultTitle?: string;
};

export function SeoMetaEditor({ entityType, entityId, defaultTitle }: Props) {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [data, setData] = useState<SeoMetaResponse | null>(null);
  const [form, setForm] = useState({
    title: '',
    description: '',
    h1: '',
    canonicalUrl: '',
    robots: '',
    ogTitle: '',
    ogDescription: '',
    ogImage: '',
    jsonLdText: '',
  });

  const counters = useMemo(
    () => ({
      title: form.title.length,
      description: form.description.length,
      h1: form.h1.length,
    }),
    [form],
  );

  useEffect(() => {
    let mounted = true;
    getSeo(entityType, entityId)
      .then((seo) => {
        if (!mounted) return;
        setData(seo);
        setForm({
          title: seo.title ?? defaultTitle ?? '',
          description: seo.description ?? '',
          h1: seo.h1 ?? '',
          canonicalUrl: seo.canonicalUrl ?? '',
          robots: seo.robots ?? '',
          ogTitle: seo.ogTitle ?? '',
          ogDescription: seo.ogDescription ?? '',
          ogImage: seo.ogImage ?? '',
          jsonLdText: seo.jsonLd ? JSON.stringify(seo.jsonLd, null, 2) : '',
        });
      })
      .catch(() => {
        if (mounted) setForm({ title: defaultTitle ?? '', description: '', h1: '', canonicalUrl: '', robots: '', ogTitle: '', ogDescription: '', ogImage: '', jsonLdText: '' });
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [entityType, entityId, defaultTitle]);

  const onChange = (k: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm((p) => ({ ...p, [k]: e.target.value }));
  };

  const onGenerate = async () => {
    setSaving(true);
    try {
      const seo = await generateSeo(entityType, entityId);
      setData(seo);
      setForm({
        title: seo.title ?? '',
        description: seo.description ?? '',
        h1: seo.h1 ?? '',
        canonicalUrl: seo.canonicalUrl ?? '',
        robots: seo.robots ?? '',
        ogTitle: seo.ogTitle ?? '',
        ogDescription: seo.ogDescription ?? '',
        ogImage: seo.ogImage ?? '',
        jsonLdText: seo.jsonLd ? JSON.stringify(seo.jsonLd, null, 2) : '',
      });
    } finally {
      setSaving(false);
    }
  };

  const onSave = async () => {
    setSaving(true);
    try {
      let jsonLd: Record<string, unknown> | null = null;
      if (form.jsonLdText.trim()) {
        try {
          jsonLd = JSON.parse(form.jsonLdText);
        } catch {
          return;
        }
      }
      const payload = {
        title: form.title.trim() || null,
        description: form.description.trim() || null,
        h1: form.h1.trim() || null,
        canonicalUrl: form.canonicalUrl.trim() || null,
        robots: form.robots.trim() || null,
        ogTitle: form.ogTitle.trim() || null,
        ogDescription: form.ogDescription.trim() || null,
        ogImage: form.ogImage.trim() || null,
        jsonLd,
        autoGenerated: false,
      };
      const seo = await upsertSeo(entityType, entityId, payload);
      setData({ ...seo, source: 'manual' });
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="rounded-xl border border-gray-200 bg-white p-4 text-sm text-gray-600">Загрузка SEO…</div>;
  }

  const seoStatus = data?.source === 'manual' ? 'MANUAL' : data?.source === 'auto' ? 'AUTO' : 'DEFAULT';
  const titleOk = form.title.trim().length >= 10;
  const descOk = form.description.trim().length >= 50;

  return (
    <div className="space-y-4 rounded-xl border border-gray-200 bg-white p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="text-sm font-semibold">SEO</div>
          <div className="text-xs text-gray-600">Источник: {seoStatus}</div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={onGenerate} disabled={saving}>
            Сгенерировать
          </Button>
          <Button size="sm" onClick={onSave} disabled={saving || !titleOk || !descOk}>
            Сохранить
          </Button>
        </div>
      </div>

      <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 text-xs">
        <div className="text-green-700">daibilet.ru</div>
        <div className="mt-0.5 font-medium text-blue-700">{form.title || '—'}</div>
        <div className="text-gray-600">{form.description || '—'}</div>
      </div>

      <div className="grid gap-3">
        <div>
          <div className="mb-1 flex justify-between">
            <Label>Meta title</Label>
            <span className={`text-xs ${counters.title > 60 ? 'text-red-600' : 'text-gray-500'}`}>
              {counters.title}/60
            </span>
          </div>
          <Input value={form.title} onChange={onChange('title')} placeholder="До 60 символов" />
        </div>
        <div>
          <div className="mb-1 flex justify-between">
            <Label>Meta description</Label>
            <span className={`text-xs ${counters.description > 160 ? 'text-red-600' : 'text-gray-500'}`}>
              {counters.description}/160
            </span>
          </div>
          <Textarea
            value={form.description}
            onChange={onChange('description')}
            rows={3}
            placeholder="До 160 символов"
          />
        </div>
        <div>
          <div className="mb-1 flex justify-between">
            <Label>H1</Label>
            <span className="text-xs text-gray-500">{counters.h1}/120</span>
          </div>
          <Input value={form.h1} onChange={onChange('h1')} />
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <Label>Canonical URL</Label>
            <Input value={form.canonicalUrl} onChange={onChange('canonicalUrl')} placeholder="Опционально" />
          </div>
          <div>
            <Label>Robots</Label>
            <Input
              value={form.robots}
              onChange={onChange('robots')}
              placeholder="index,follow"
            />
          </div>
        </div>
        <div className="grid gap-3 sm:grid-cols-3">
          <div>
            <Label>OG title</Label>
            <Input value={form.ogTitle} onChange={onChange('ogTitle')} />
          </div>
          <div className="sm:col-span-2">
            <Label>OG description</Label>
            <Input value={form.ogDescription} onChange={onChange('ogDescription')} />
          </div>
        </div>
        <div>
          <Label>OG image URL</Label>
          <Input value={form.ogImage} onChange={onChange('ogImage')} placeholder="https://..." />
        </div>
        <div>
          <Label>JSON-LD (опционально)</Label>
          <Textarea
            value={form.jsonLdText}
            onChange={onChange('jsonLdText')}
            rows={8}
            className="font-mono text-xs"
            placeholder='{"@context":"https://schema.org","@type":"Event",...}'
          />
        </div>
        {(!titleOk || !descOk) && (
          <p className="text-xs text-amber-700">
            Для сохранения: title ≥ 10 символов и description ≥ 50 символов.
          </p>
        )}
      </div>
    </div>
  );
}
