/**
 * SeoMeta — универсальный SEO-блок для City, Event, Venue, Landing, Article, Combo.
 * См. docs/seo/SeoMetaSpec.md
 */
import { Injectable, NotFoundException } from '@nestjs/common';
import type { SeoEntityType } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { UpsertSeoMetaDto } from './dto/upsert-seo-meta.dto';
import type { SeoMetaResponse } from './dto/seo-meta.response';

type BaseEntity = {
  id: string;
  slug?: string | null;
  title?: string | null;
  name?: string | null;
  cityName?: string | null;
  priceFrom?: number | null;
  imageUrl?: string | null;
  category?: string | null;
  subcategories?: string[] | null;
};

const SITE_URL = 'https://daibilet.ru';

@Injectable()
export class SeoMetaService {
  constructor(private readonly prisma: PrismaService) {}

  async getSeoMeta(entityType: SeoEntityType, entityId: string): Promise<SeoMetaResponse> {
    const seo = await this.prisma.seoMeta.findUnique({
      where: { entityType_entityId: { entityType, entityId } },
    });

    if (seo) {
      const source: SeoMetaResponse['source'] = seo.autoGenerated ? 'auto' : 'manual';
      return { ...this.toResponse(seo), source } as SeoMetaResponse;
    }

    const def = await this.computeDefaultSeo(entityType, entityId);
    return { ...def, source: 'default' } as SeoMetaResponse;
  }

  async upsertSeoMeta(entityType: SeoEntityType, entityId: string, dto: UpsertSeoMetaDto) {
    const autoGenerated = dto.autoGenerated ?? false;

    const saved = await this.prisma.seoMeta.upsert({
      where: { entityType_entityId: { entityType, entityId } },
      create: { entityType, entityId, ...this.sanitizeDto(dto), autoGenerated },
      update: { ...this.sanitizeDto(dto), autoGenerated },
    });

    return this.toResponse(saved);
  }

  async generateSeoMeta(entityType: SeoEntityType, entityId: string) {
    const generated = await this.generateFromEntity(entityType, entityId);

    const saved = await this.prisma.seoMeta.upsert({
      where: { entityType_entityId: { entityType, entityId } },
      create: { entityType, entityId, ...generated, autoGenerated: true },
      update: { ...generated, autoGenerated: true },
    });

    return this.toResponse(saved);
  }

  private sanitizeDto(dto: UpsertSeoMetaDto) {
    return {
      title: dto.title?.trim() || null,
      description: dto.description?.trim() || null,
      h1: dto.h1?.trim() || null,
      canonicalUrl: dto.canonicalUrl?.trim() || null,
      robots: dto.robots?.trim() || null,
      ogTitle: dto.ogTitle?.trim() || null,
      ogDescription: dto.ogDescription?.trim() || null,
      ogImage: dto.ogImage?.trim() || null,
      jsonLd: dto.jsonLd ?? null,
    };
  }

  private toResponse(seo: { entityType: SeoEntityType; entityId: string } & Record<string, unknown>) {
    return {
      entityType: seo.entityType,
      entityId: seo.entityId,
      title: (seo.title as string) ?? null,
      description: (seo.description as string) ?? null,
      h1: (seo.h1 as string) ?? null,
      canonicalUrl: (seo.canonicalUrl as string) ?? null,
      robots: (seo.robots as string) ?? null,
      ogTitle: (seo.ogTitle as string) ?? null,
      ogDescription: (seo.ogDescription as string) ?? null,
      ogImage: (seo.ogImage as string) ?? null,
      jsonLd: (seo.jsonLd as Record<string, unknown>) ?? null,
      autoGenerated: Boolean(seo.autoGenerated),
    };
  }

  private async computeDefaultSeo(entityType: SeoEntityType, entityId: string) {
    const entity = await this.loadEntity(entityType, entityId);
    const title = entity.title ?? entity.name ?? 'Daibilet';
    const city = entity.cityName ?? '';

    return {
      entityType,
      entityId,
      title: city ? `${title} — ${city}` : title,
      description: city ? `Билеты и подборки в ${city}. Актуальные цены, расписание и отзывы.` : `Билеты и подборки. Актуальные цены, расписание и отзывы.`,
      h1: title,
      canonicalUrl: null,
      robots: 'index,follow',
      ogTitle: null,
      ogDescription: null,
      ogImage: entity.imageUrl ?? null,
      jsonLd: null,
      autoGenerated: false,
    };
  }

  private async generateFromEntity(entityType: SeoEntityType, entityId: string) {
    const e = await this.loadEntity(entityType, entityId);

    const title = (e.title ?? e.name ?? '').trim();
    const cityName = e.cityName ?? '';
    const priceFrom = typeof e.priceFrom === 'number' && e.priceFrom > 0 ? Math.round(e.priceFrom / 100) : null;

    if (entityType === 'CITY') {
      const city = cityName || title || 'город';
      return {
        title: `Экскурсии, музеи и мероприятия в ${city} — купить билеты онлайн`,
        description: `Подборка экскурсий, музеев и мероприятий в ${city}. Цены, расписание, отзывы и покупка онлайн.`,
        h1: `Билеты и события в ${city}`,
        ogTitle: `Что посетить в ${city}`,
        ogDescription: `Экскурсии, музеи, мероприятия — билеты онлайн.`,
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: { '@context': 'https://schema.org', '@type': 'TouristDestination', name: city },
      };
    }

    if (entityType === 'VENUE') {
      const city = cityName ? ` | ${cityName}` : '';
      return {
        title: `${title} — режим работы, билеты, адрес${city}`,
        description: `${title}${cityName ? ` в ${cityName}` : ''}: режим работы, адрес, билеты онлайн и отзывы.`,
        h1: title,
        ogTitle: title,
        ogDescription: 'Режим работы, адрес, билеты онлайн.',
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: { '@context': 'https://schema.org', '@type': 'TouristAttraction', name: title },
      };
    }

    if (entityType === 'EVENT') {
      const city = cityName ? ` в ${cityName}` : '';
      const pricePart = priceFrom ? ` — билеты от ${priceFrom} ₽` : '';
      return {
        title: `${title}${city}${pricePart} | Daibilet`,
        description: `Купить билеты на "${title}"${cityName ? ` в ${cityName}` : ''}. Актуальное расписание, цены и отзывы. Онлайн-оплата.`,
        h1: title,
        ogTitle: title,
        ogDescription: priceFrom ? `Билеты от ${priceFrom} ₽. Расписание и отзывы.` : 'Расписание и отзывы. Онлайн-оплата.',
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: null,
      };
    }

    if (entityType === 'LANDING') {
      const city = cityName ? ` — ${cityName}` : '';
      return {
        title: `${title}${city} | Подборка`,
        description: `Подборка: ${title}${cityName ? ` в ${cityName}` : ''}. Выборка лучших вариантов, цены и билеты онлайн.`,
        h1: title,
        ogTitle: title,
        ogDescription: 'Подборка и билеты онлайн.',
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: null,
      };
    }

    if (entityType === 'ARTICLE') {
      const city = cityName ? ` — ${cityName}` : '';
      return {
        title: `${title}${city} | Блог Daibilet`,
        description: `${title}${cityName ? `: ${cityName}` : ''}. Гид, советы и подборки с привязкой к билетам.`,
        h1: title,
        ogTitle: title,
        ogDescription: 'Гид и подборки с билетами.',
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: null,
      };
    }

    if (entityType === 'COMBO') {
      const city = cityName ? ` — ${cityName}` : '';
      return {
        title: `${title}${city} | Маршрут и билеты`,
        description: `Готовая программа: ${title}${cityName ? ` в ${cityName}` : ''}. Билеты, время, логика маршрута.`,
        h1: title,
        ogTitle: title,
        ogDescription: 'Готовая программа и билеты.',
        ogImage: e.imageUrl ?? null,
        robots: 'index,follow',
        canonicalUrl: null,
        jsonLd: null,
      };
    }

    return this.computeDefaultSeo(entityType, entityId);
  }

  private async loadEntity(entityType: SeoEntityType, entityId: string): Promise<BaseEntity> {
    switch (entityType) {
      case 'CITY': {
        const city = await this.prisma.city.findUnique({ where: { id: entityId } });
        if (!city) throw new NotFoundException('City not found');
        return {
          id: city.id,
          name: city.name,
          slug: city.slug,
          cityName: city.name,
          imageUrl: city.heroImage ?? null,
        };
      }
      case 'EVENT': {
        const ev = await this.prisma.event.findUnique({
          where: { id: entityId },
          include: { city: { select: { name: true } } },
        });
        if (!ev) throw new NotFoundException('Event not found');
        return {
          id: ev.id,
          slug: ev.slug,
          title: ev.title,
          cityName: ev.city?.name ?? null,
          priceFrom: ev.priceFrom,
          imageUrl: ev.imageUrl ?? null,
          category: ev.category,
          subcategories: ev.subcategories,
        };
      }
      case 'VENUE': {
        const v = await this.prisma.venue.findUnique({
          where: { id: entityId },
          include: { city: { select: { name: true } } },
        });
        if (!v) throw new NotFoundException('Venue not found');
        return {
          id: v.id,
          slug: v.slug,
          title: v.title,
          cityName: v.city?.name ?? null,
          priceFrom: v.priceFrom,
          imageUrl: v.imageUrl ?? null,
        };
      }
      case 'LANDING': {
        const lp = await this.prisma.landingPage.findUnique({
          where: { id: entityId },
          include: { city: { select: { name: true } } },
        });
        if (!lp) throw new NotFoundException('LandingPage not found');
        return {
          id: lp.id,
          slug: lp.slug,
          title: lp.title,
          cityName: lp.city?.name ?? null,
          imageUrl: null,
        };
      }
      case 'ARTICLE': {
        const a = await this.prisma.article.findUnique({
          where: { id: entityId },
          include: { city: { select: { name: true } } },
        });
        if (!a) throw new NotFoundException('Article not found');
        return {
          id: a.id,
          slug: a.slug,
          title: a.title,
          cityName: a.city?.name ?? null,
          imageUrl: a.coverImage ?? null,
        };
      }
      case 'COMBO': {
        const c = await this.prisma.comboPage.findUnique({
          where: { id: entityId },
          include: { city: { select: { name: true } } },
        });
        if (!c) throw new NotFoundException('ComboPage not found');
        return {
          id: c.id,
          slug: c.slug,
          title: c.title,
          cityName: c.city?.name ?? null,
          imageUrl: c.heroImage ?? null,
        };
      }
      default:
        throw new NotFoundException('Unsupported entity type');
    }
  }
}
