/**
 * API response types for frontend api.ts.
 * Shared types (CatalogItem, EventDetail, etc.) come from @daibilet/shared.
 */

import type { TagItem } from '@daibilet/shared';

/** SEO meta (GET /seo/:entityType/:entityId) */
export interface SeoMetaResponse {
  entityType?: string;
  entityId?: string;
  title?: string | null;
  description?: string | null;
  h1?: string | null;
  canonicalUrl?: string | null;
  robots?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: string | null;
  jsonLd?: Record<string, unknown> | null;
  autoGenerated?: boolean;
  source?: 'manual' | 'auto' | 'default';
}

/** POST /checkout/validate-gift-certificate */
export interface ValidateGiftCertificateResponse {
  valid: boolean;
  discountAmount?: number;
  amount?: number;
  message?: string;
}

/** Planner calculate meta */
export interface PlanCalculateMeta {
  city?: string;
  dateFrom?: string;
  dateTo?: string;
  [key: string]: unknown;
}

/** Location (причал, точка встречи) */
export interface LocationItem {
  id: string;
  type: string;
  title: string;
  shortTitle?: string | null;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  metro?: string | null;
  district?: string | null;
  city?: { id: string; slug: string; name: string };
}

/** City detail (getCityBySlug) */
export interface CityDetail {
  id: string;
  slug: string;
  name: string;
  heroImage: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  _count?: { events: number };
  [key: string]: unknown;
}

/** Tag page (getTagBySlug) */
export interface TagDetailPage {
  tag: {
    id: string;
    slug: string;
    name: string;
    category?: string;
    metaTitle?: string | null;
    metaDescription?: string | null;
    description?: string | null;
  };
  events?: unknown[];
  total?: number;
  page?: number;
  [key: string]: unknown;
}

/** Article list item */
export interface ArticleListItem {
  id: string;
  slug: string;
  title: string;
  excerpt?: string | null;
  imageUrl?: string | null;
  publishedAt?: string;
  [key: string]: unknown;
}

/** Article detail */
export interface ArticleDetail {
  id: string;
  slug: string;
  title: string;
  content?: string | null;
  excerpt?: string | null;
  imageUrl?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  publishedAt?: string;
  [key: string]: unknown;
}

/** Region detail */
export interface RegionDetail {
  id: string;
  slug: string;
  name: string;
  [key: string]: unknown;
}

/** Landing / Collection / Combo (минимальные поля) */
export interface LandingItem {
  id: string;
  slug: string;
  title: string;
  [key: string]: unknown;
}

/** Landing page response (GET /landings/:slug) — landing, variants, filters, total */
export interface LandingPageResponse {
  landing: LandingItem & {
    metaTitle?: string | null;
    metaDescription?: string | null;
    subtitle?: string | null;
    city?: { slug: string; name: string } | null;
    stats?: { totalSold?: number; soldTickets?: number; avgRating?: number } | null;
    howToChoose?: unknown[];
    infoBlocks?: unknown[];
    faq?: unknown[];
    reviews?: unknown[];
    relatedLinks?: unknown[];
    legalText?: string | null;
  };
  variants?: unknown[];
  filters?: unknown[];
  total?: number;
}

/** Collection detail (getCollectionBySlug) — backend возвращает { collection, items, ... } */
export interface CollectionDetailResponse {
  collection: {
    id: string;
    slug: string;
    title: string;
    subtitle?: string | null;
    heroImage?: string | null;
    description?: string | null;
    metaTitle?: string | null;
    metaDescription?: string | null;
    infoBlocks?: unknown;
    faq?: unknown;
    city?: { id: string; name: string; slug: string } | null;
  };
  items?: unknown[];
  total?: number;
  page?: number;
  totalPages?: number;
  pinnedEvents?: unknown[];
  relatedCollections?: unknown[];
}

/** Review item (backend shape) — совместим с ReviewSection.ReviewItem */
export interface ReviewItemDto {
  id: string;
  rating: number;
  title?: string;
  text: string;
  authorName: string;
  isVerified: boolean;
  helpfulCount: number;
  createdAt: string;
  photos: { id: string; url: string; thumbUrl: string }[];
}

/** External review item */
export interface ExternalReviewItemDto {
  id: string;
  source: string;
  sourceUrl?: string;
  authorName: string;
  rating: number;
  text: string;
  publishedAt?: string;
}

/** Результат поиска (GET /search) */
export interface SearchResult {
  events: import('@daibilet/shared').EventListItem[];
  cities: import('@daibilet/shared').CityListItem[];
}

/** Ответ статуса checkout (GET /checkout/:packageId/status) */
export interface CheckoutStatusResponse {
  status: string;
  voucherUrl: string | null;
  totalPrice?: number;
  items?: unknown[];
  code?: string;
}

/** Tag с счётчиком событий (API /tags) */
export interface TagWithCount extends TagItem {
  _count?: { events: number };
}

/** Combo detail — features, faq, days, upsells */
export interface ComboDetailData {
  features?: Array<{ icon?: string; title?: string; text?: string }>;
  faq?: Array<{ question?: string; answer?: string }>;
  days?: Array<{ dayNumber?: number; slots?: Array<{ slot?: string; event?: unknown; subtotal?: number }> }>;
  upsells?: Array<{ id?: string; name?: string; priceKopecks?: number; icon?: string }>;
}

/** Review response (paginated) — совместим с ReviewSection */
export interface ReviewsResponse {
  items: ReviewItemDto[];
  externalReviews: ExternalReviewItemDto[];
  total: number;
  page: number;
  totalPages: number;
  summary: {
    avgRating: number;
    reviewCount: number;
    verifiedCount: number;
    distribution: Record<number, number>;
  };
}
