import type { SeoEntityType } from '@prisma/client';

export type SeoMetaResponse = {
  entityType: SeoEntityType;
  entityId: string;
  title: string | null;
  description: string | null;
  h1: string | null;
  canonicalUrl: string | null;
  robots: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;
  jsonLd: Record<string, unknown> | null;
  autoGenerated: boolean;
  source: 'manual' | 'auto' | 'default';
};
