import { IsBoolean, IsObject, IsOptional, IsString, MaxLength } from 'class-validator';

export class UpsertSeoMetaDto {
  @IsOptional() @IsString() @MaxLength(90)
  title?: string;

  @IsOptional() @IsString() @MaxLength(200)
  description?: string;

  @IsOptional() @IsString() @MaxLength(120)
  h1?: string;

  @IsOptional() @IsString() @MaxLength(400)
  canonicalUrl?: string;

  @IsOptional() @IsString() @MaxLength(40)
  robots?: string;

  @IsOptional() @IsString() @MaxLength(90)
  ogTitle?: string;

  @IsOptional() @IsString() @MaxLength(200)
  ogDescription?: string;

  @IsOptional() @IsString() @MaxLength(400)
  ogImage?: string;

  @IsOptional() @IsObject()
  jsonLd?: Record<string, unknown>;

  @IsOptional() @IsBoolean()
  autoGenerated?: boolean;
}
