-- CreateEnum
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'SeoEntityType') THEN
    CREATE TYPE "SeoEntityType" AS ENUM ('CITY','EVENT','VENUE','LANDING','ARTICLE','COMBO');
  END IF;
END$$;

-- CreateTable
CREATE TABLE IF NOT EXISTS "seo_meta" (
    "id"            TEXT NOT NULL,
    "entityType"    "SeoEntityType" NOT NULL,
    "entityId"      TEXT NOT NULL,
    "title"         TEXT,
    "description"   TEXT,
    "h1"            TEXT,
    "canonicalUrl"  TEXT,
    "robots"        TEXT,
    "ogTitle"       TEXT,
    "ogDescription" TEXT,
    "ogImage"       TEXT,
    "jsonLd"        JSONB,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "seo_meta_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "seo_meta_entityType_entityId_key" ON "seo_meta"("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "seo_meta_entityType_idx" ON "seo_meta"("entityType");
CREATE INDEX IF NOT EXISTS "seo_meta_entityId_idx" ON "seo_meta"("entityId");
